# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.3

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.3.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.3.1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/Sean/dev/grav_proc_unit

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/Sean/dev/grav_proc_unit

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.3.1/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.3.1/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/Sean/dev/grav_proc_unit/CMakeFiles /Users/Sean/dev/grav_proc_unit/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/Sean/dev/grav_proc_unit/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gpu

# Build rule for target.
gpu: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gpu
.PHONY : gpu

# fast build rule for target.
gpu/fast:
	$(MAKE) -f CMakeFiles/gpu.dir/build.make CMakeFiles/gpu.dir/build
.PHONY : gpu/fast

#=============================================================================
# Target rules for targets named gpu_lib

# Build rule for target.
gpu_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gpu_lib
.PHONY : gpu_lib

# fast build rule for target.
gpu_lib/fast:
	$(MAKE) -f CMakeFiles/gpu_lib.dir/build.make CMakeFiles/gpu_lib.dir/build
.PHONY : gpu_lib/fast

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/gpu.dir/build.make CMakeFiles/gpu.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/gpu.dir/build.make CMakeFiles/gpu.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/gpu.dir/build.make CMakeFiles/gpu.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/test.o: src/test.cpp.o

.PHONY : src/test.o

# target to build an object file
src/test.cpp.o:
	$(MAKE) -f CMakeFiles/gpu_lib.dir/build.make CMakeFiles/gpu_lib.dir/src/test.cpp.o
.PHONY : src/test.cpp.o

src/test.i: src/test.cpp.i

.PHONY : src/test.i

# target to preprocess a source file
src/test.cpp.i:
	$(MAKE) -f CMakeFiles/gpu_lib.dir/build.make CMakeFiles/gpu_lib.dir/src/test.cpp.i
.PHONY : src/test.cpp.i

src/test.s: src/test.cpp.s

.PHONY : src/test.s

# target to generate assembly for a file
src/test.cpp.s:
	$(MAKE) -f CMakeFiles/gpu_lib.dir/build.make CMakeFiles/gpu_lib.dir/src/test.cpp.s
.PHONY : src/test.cpp.s

src/testdir/test.o: src/testdir/test.cpp.o

.PHONY : src/testdir/test.o

# target to build an object file
src/testdir/test.cpp.o:
	$(MAKE) -f CMakeFiles/gpu_lib.dir/build.make CMakeFiles/gpu_lib.dir/src/testdir/test.cpp.o
.PHONY : src/testdir/test.cpp.o

src/testdir/test.i: src/testdir/test.cpp.i

.PHONY : src/testdir/test.i

# target to preprocess a source file
src/testdir/test.cpp.i:
	$(MAKE) -f CMakeFiles/gpu_lib.dir/build.make CMakeFiles/gpu_lib.dir/src/testdir/test.cpp.i
.PHONY : src/testdir/test.cpp.i

src/testdir/test.s: src/testdir/test.cpp.s

.PHONY : src/testdir/test.s

# target to generate assembly for a file
src/testdir/test.cpp.s:
	$(MAKE) -f CMakeFiles/gpu_lib.dir/build.make CMakeFiles/gpu_lib.dir/src/testdir/test.cpp.s
.PHONY : src/testdir/test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... gpu"
	@echo "... gpu_lib"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/test.o"
	@echo "... src/test.i"
	@echo "... src/test.s"
	@echo "... src/testdir/test.o"
	@echo "... src/testdir/test.i"
	@echo "... src/testdir/test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

